### ISSUE TITLE
Cannot read property 'protocol' of undefined

### ISSUE THREAD

**Issue by picsoung** [joncursi/socket-io-client#4]
Hey,

I am trying to connect to some Slack Websocket `var url = wss://ms122.slack-msgs.com/websocket/LONG_STRANGE_ID`

in my code I do

``` js
        var socket = io(url);
        socket.on('connect', Meteor.bindEnvironment(function() {
          console.log('Connected to the websocket!');
          // on data event
          socket.on('hello', Meteor.bindEnvironment(function(data) {
            console.log(data);
          }, function(e) {
            throw e;
          }));

        }, function(e) {
          throw e;
        }));
```

but it throws 

```
Exception in callback of async function: TypeError: Cannot read property 'protocol' of undefined
  at url (/Users/picsoung/.meteor/packages/joncursi_socket-io-client/.0.1.4.17780oj++os+web.browser+web.cordova/npm/node_modules/socket.io-client/lib/url.js:29:29)
  at lookup (/Users/picsoung/.meteor/packages/joncursi_socket-io-client/.0.1.4.17780oj++os+web.browser+web.cordova/npm/node_modules/socket.io-client/lib/index.js:44:16)
   at app/methods/method.slack.js:11:22
  at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
```

any idea how I can solve this?
Thanks

**Comment by joncursi** [comment]
Hmm, I could be wrong but this appears to be an implementation issue with Slack rather than an issue with the socket-io-client library. Were you able to resolve?
