### ISSUE TITLE
io is undefined in package

### ISSUE THREAD

**Issue by harishreddy-m** [joncursi/socket-io-client#7]
I am trying to use this package as dependency for my package
``` 
  var packages = [
        'ecmascript',
        'joncursi:socket-io-client'
    ];

    api.use(packages);
```
Trying to use in my package file as 
`import io from 'meteor/joncursi:socket-io-client'`

When I debugged in chrome inspector as I was running tests for my package.
![screenshot from 2016-12-23 14 15 36](https://cloud.githubusercontent.com/assets/592646/21450257/2770cc1a-c91b-11e6-8935-e367a638d6df.png)

I took a look at your code.There is api.export(io) 
But still io is undefined

**Comment by joncursi** [comment]
What version of Meteor are you on? I wouldn't recommend using this package if your Meteor version > 1.3. You can install socketio directly from npm if you're using any recent version of Meteor, which is highly recommended

**Comment by harishreddy-m** [comment]
I am on meteor 1.4.2.3 version.
I tried Npm.depends() also.
I was getting error 

```
harish:communication: updating npm dependencies -- socket.io-client...
/home/harishreddy/.meteor/packages/ecmascript/.0.5.9.ui3230++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

Error: ENOENT: no such file or directory, lstat '/home/harishreddy/meteorPackages/communication/.npm/package/node_modules'
    at Error (native)
    at Object.fs.lstatSync (fs.js:839:18)
    at Object.wrapper (/tools/fs/files.js:1535:35)
    at files.(anonymous function) (/tools/fs/files.js:1636:27)
    at wrap.makeCacheKey._len2 (/tools/fs/optimistic.js:22:15)
    at Entry._reallyRecompute (/home/harishreddy/.meteor/packages/meteor-tool/.1.4.2_3.h5rt9d++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:215:26)
    at Entry._recomputeIfDirty (/home/harishreddy/.meteor/packages/meteor-tool/.1.4.2_3.h5rt9d++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:179:17)
    at Entry.recompute (/home/harishreddy/.meteor/packages/meteor-tool/.1.4.2_3.h5rt9d++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:46:20)
    at optimistic (/home/harishreddy/.meteor/packages/meteor-tool/.1.4.2_3.h5rt9d++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/lib/index.js:50:18)
    at /tools/isobuild/meteor-npm.js:438:17
    at Object.meteorNpm.dependenciesArePortable (/tools/isobuild/meteor-npm.js:520:10)
    at NodeModulesDirectory.isPortable (/tools/isobuild/bundler.js:269:22)
    at /tools/isobuild/bundler.js:1975:17
    at Function._.each._.forEach (/home/harishreddy/.meteor/packages/meteor-tool/.1.4.2_3.h5rt9d++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at JsImage.write (/tools/isobuild/bundler.js:1972:7)
    at ServerTarget.write (/tools/isobuild/bundler.js:2241:13)
    at /tools/isobuild/bundler.js:2336:30
    at /tools/isobuild/bundler.js:2469:9
    at Array.forEach (native)
    at /tools/isobuild/bundler.js:2459:26
    at /tools/isobuild/bundler.js:2399:7
    at /tools/isobuild/bundler.js:2800:22
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundle (/tools/isobuild/bundler.js:2633:31)
    at /tools/isobuild/bundler.js:2580:32
    at Object.withCache (/tools/fs/files.js:1601:12)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2580:16)
    at /tools/runners/run-app.js:574:36
    at Function.run (/tools/tool-env/profile.js:490:12)
    at bundleApp (/tools/runners/run-app.js:573:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:617:35)
    at AppRunner._fiber (/tools/runners/run-app.js:876:28)
    at /tools/runners/run-app.js:403:12

```

**Comment by harishreddy-m** [comment]
> As of writing, we can only load NPM packages using this method on the server. This is due to the nature of how Node works as a server-side environment.

I think this might be the problem, as your package uses Npm.depends()

**Comment by joncursi** [comment]
See: https://github.com/joncursi/socket-io-client#meteor-13
